name: Deploy Vulnerable Application                                  # workflow name

on:
  push:
    branches:
      - master
jobs:
  deploy-heroku:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "app-vulnerable2022-hackademy-gkarp" #Must be unique in Heroku
          heroku_email: "ggckarp@gmail.com"
          remote_branch: "master"
          usedocker: true
