name: Horusec scan

on:
  push:
    branches:
      - master
jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - name: Run Horusec // source https://docs.horusec.io/docs/cli/installation/
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" --config-file-path horusec-config.json
      
      - name: Upload  security scan result
        uses: actions/upload-artifact@v3
        with:
          name: horusec
          path: horusec-config.json